### ISSUE TITLE
Character runs automatically

### ISSUE THREAD

**Issue by Mjons** [decentraland/explorer-desktop#361]
### What happened?

i have this aweful issue i have not been able to shake... my character in DCL constantly runs down and to the right. no matter what i do this continues.
Any insights on how to fix this?

https://user-images.githubusercontent.com/7331236/179851735-cc2e9c16-05f3-425e-abdf-0eb007c23ba0.mp4

### Steps to reproduce

not sure

### Operating System

Chrome, Windows 10

### Wallet

Metamask

### CPU

Intel Core I9 10980XE

### GPU

NVIDIO Quadro P6000

### RAM

80GB

### Kernel Version

unknown-kernel-version

### Unity Version

unknown-renderer-version

### Realm

it happens in all realms and in the SDK too

### NameTag

UnrealApe

**Comment by Mjons** [comment]
I do not have any joystick connected. I tried to unplug all of my inputs but still no luck with this issue.

**Comment by JorgeDecentraland** [comment]
@kwssbocian could you try to reproduce this issue, please?

**Comment by Mjons** [comment]
lol yes it happens everytime i log into decentraland without me pressing
anything
Michael Jonsson

about.me/michaeljonsson

**Comment by kwssbocian** [comment]
@JorgeDecentraland Unfortunately I was unable to reproduce the issue on my end so far. I have attempted on Windows web and desktop with and without controllers and on MacOS as well for good measure. At no point was I getting any sort of spontaneous movement.

**Comment by Mjons** [comment]
Ok, thanks for letting me know.  But of course i would not expect you to
reproduce this problem.
I assume most people don't turn on decentraland only to see their avatar
run in 1 direction for no reason or you guys would have a big problem...

Consider finding someone who understands to jump on a call/screen share and
actually investigate the problem properly?
Just an idea... instead of wasting time with telling me hope you can't
reproduce the problem.

If i could reproduce the problem on another machine, then i probably would
not have a problem anymore because i would be able to troubleshoot it
properly

This has been an issue for about 6 months and is making it very hard to
develop in dcl...
Thanks for your time

**Comment by Antivortex** [comment]
Hello @Mjons 

Please try if the issue is still present for you in this test build:
https://play.decentraland.zone/?renderer-branch=dev-joystick-input-disabled

If this issue is only reproducible in local build you do then this is the branch to make local build and test the fix:

https://github.com/decentraland/unity-renderer/tree/dev-joystick-input-disabled

Let us know if it is still there, thank you

**Comment by Mjons** [comment]
Here is a video of me clicking the link you suggested. This time i am
running up and to the left instead of down and to the right.
 2022-08-31 08-55-52.mp4
<https://drive.google.com/file/d/154yMnyFspOXCRB06xP5x8HfadBQD-hkh/view?usp=drive_web>

Michael Jonsson

about.me/michaeljonsson

**Comment by Antivortex** [comment]
@Mjons 

The change in the character autorun direction tells us that most likely this problem is related to your local input drivers, cache or settings.

I tried one other modification on our side, you can check it by the same link: https://play.decentraland.zone/?renderer-branch=dev-joystick-input-disabled

If the problem still persists for you try using Firefox browser instead of Chrome (you can play as Guest in Firefox if you do not want to transfer your Metamask there). If it will be okay in Firefox then you can clear your Decentraland cookies in Chrome settings to fix it in Chrome or you could do that even before trying Firefox.  (Settings -> Privacy and Security -> Cookies and site data -> See all cookies and site data -> search for Decentraland). Make sure you have access to your Metamask wallet before deleting cookies.

If it persists in Firefox and after cleaning cookies you could:

1) Disconnect all of the input devices in Windows Bluetooth settings which are considered Paired or Connected if there are any like that. 
2) Go to Device Manager -> Human Interface Devices and send us a screenshot of the list of devices you see there.

**Comment by Mjons** [comment]
Hi there,

I am hoping to find a solution to this issue so I can build/test more
effectively
Can you let me know what the next steps are?

Michael Jonsson

about.me/michaeljonsson

**Comment by Antivortex** [comment]
@Mjons 

Hello, great to hear it is fixed for your browser.

Did you mean it is fixed in this link ( https://play.decentraland.zone/?renderer-branch=dev-joystick-input-disabled ) without any cookies cleaning or it was fixed after you cleaned the cookies?

Please make sure to reply to this thread directly (not e-mail) for us to see your reply.

**Comment by Antivortex** [comment]
@Mjons 

Thank you, the link was just a test version to check if one fix works for your local machine. Now that we know it works we will include this fix to the next release in both web and desktop, I will let you know when this release will be live.

**Comment by Mjons** [comment]
It seems that the new patch has fixed my issue in game. but in the SDK it still is broken!

**Comment by Mjons** [comment]
Any chance we can reopen this? I am super happy that this issue was fixed in the game itself. 
But when i am testing in the SDK the problem persists where my character walks in a single direction unprompted.
Thanks!

**Comment by Mjons** [comment]
It worked!
I tried in both chrome and firefox and had no issues this time (which is
really nice)

When i open it in the desktop client the issue persists though.

What are the next steps?

Michael Jonsson

about.me/michaeljonsson
